In [ ]:
from utils.log_datasets import OutcomeDataset

In [2]:
dataset_name = 'Traffic_Fines'
dataset_folder = '../datasets/raw'
labels_folder = '../datasets/labels'

dataset = OutcomeDataset(
    dataset_name=dataset_name,
    dataset_folder=dataset_folder,
    labels_folder=labels_folder,
    feature_names=[
        'time_since_start',
        'time_since_last_event',
        'event_index',
        'day_of_week',
        'hour_of_day',
        'hour_sin',
        'hour_cos',
    ],
)

# Load raw data
dataset.load_and_preprocess()

Loading Traffic_Fines...

c:\Users\Pavel\Desktop\PROJECTS\master-thesis\.venv\lib\site-packages\pm4py\utils.py:990: UserWarning: In the current version, the import/export operation uses `rustxes` by default for importing/exporting files faster. Please uninstall `rustxes` to revert the behavior.
  warnings.warn(

In [3]:
dataset.raw_df.head()

,concept:name,time:timestamp,dismissal,totalPaymentAmount,points,matricola,vehicleClass,paymentAmount,lastSent,lifecycle:transition,case:concept:name,expense,amount,org:resource,notificationType,article
0,Create Fine,2006-07-23 22:00:00+00:00,NIL,0.0,0.0,NaN,A,NaN,None,complete,A1,NaN,35.0,561,None,157.0
1,Send Fine,2006-12-04 23:00:00+00:00,None,NaN,NaN,NaN,None,NaN,None,complete,A1,11.0,NaN,None,None,NaN
2,Create Fine,2006-08-01 22:00:00+00:00,NIL,0.0,0.0,NaN,A,NaN,None,complete,A100,NaN,35.0,561,None,157.0
3,Send Fine,2006-12-11 23:00:00+00:00,None,NaN,NaN,NaN,None,NaN,None,complete,A100,11.0,NaN,None,None,NaN
4,Insert Fine Notification,2007-01-14 23:00:00+00:00,None,NaN,NaN,NaN,None,NaN,P,complete,A100,NaN,NaN,None,P,NaN

In [4]:
# Split into train/test
train_df, test_df = dataset.train_test_split()

Train cases: 120296, Test cases: 30074

In [5]:
train_df.head()

,hour_sin,case:concept:name,concept:name,hour_of_day,event_index,day_of_week,time_since_start,time_since_last_event,time:timestamp,hour_cos
0,-0.500000,A1,Create Fine,22,1,6,0.000000,0.000000,2006-07-23 22:00:00+00:00,0.866025
1,-0.258819,A1,Send Fine,23,2,0,134.041667,134.041667,2006-12-04 23:00:00+00:00,0.965926
2,-0.500000,A100,Create Fine,22,1,1,0.000000,0.000000,2006-08-01 22:00:00+00:00,0.866025
3,-0.258819,A100,Send Fine,23,2,0,132.041667,132.041667,2006-12-11 23:00:00+00:00,0.965926
4,-0.258819,A100,Insert Fine Notification,23,3,6,166.041667,34.000000,2007-01-14 23:00:00+00:00,0.965926

In [6]:
# Generate prefixes
train_prefixes = dataset.get_prefixes(train_df)
test_prefixes = dataset.get_prefixes(test_df)

In [12]:
# Prepare labels
y_train = dataset.prepare_labels(train_prefixes)
y_test = dataset.prepare_labels(test_prefixes)

In [13]:
# Or directly from the original dataframes
y_train = dataset.prepare_labels(train_df)
y_test = dataset.prepare_labels(test_df)

[Outcome-Oriented Predictive Process Monitoring: Review and Benchmark](https://dl.acm.org/doi/pdf/10.1145/3301300)

Datasets:

- BPIC15_1
- BPIC15_2
- BPIC15_3
- BPIC15_4
- BPIC15_5
- Sepsis
- Traffic_Fines

Data Encodings:

- Static encoding
- Last state encoding
- Aggregation encoding
- Index-based encoding

Bucketing strategies:

- Single Bucket
- KNN
- Clustering
- Prefix Length

Methods:

- XGBoost
- RF
- Logistic Regression
- SVM

Input features can be: activity, timestamp, resource and attributes

[Features Transformers](https://github.com/nirdizati/nirdizati-training-backend/tree/master/transformers)